repos:
  - repo: local
    hooks:
      - id: ansible-playbook-check
        name: ansible playbook check
        entry: ansible-playbook --syntax-check
        language: system
        types: [yaml]
        files: "\\.ya?ml$"
        exclude: "(inventory|\\.pre-commit-config)\\.ya?ml$"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
