---
# Dependencies: pip install yamllint ansible ansible-lint

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: yaml-lint-check
        name: yaml lint check
        entry: >
          yamllint --strict
          --config-data '{
            extends: default,
            rules: {
              comments: {min-spaces-from-content: 1}
            }
          }'
        language: system
        types: [yaml]
        files: "\\.ya?ml$"
        fail_fast: true

      - id: ansible-playbook-check
        name: ansible playbook check
        entry: ansible-playbook --syntax-check
        language: system
        types: [yaml]
        files: "\\.ya?ml$"
        exclude: "\
          ^\\.pre-commit-config\\.ya?ml$|\
          ^(test|dev|prod)-env\\.ya?ml$|\
          (^|.*/)(vars|tasks|handlers)/\
          "
        fail_fast: true

      - id: ansible-lint-check
        name: ansible lint check
        entry: ansible-lint
        language: system
        types: [yaml]
        files: "\\.ya?ml$"
        exclude: "\
          ^\\.pre-commit-config\\.ya?ml$|\
          ^(test|dev|prod)-env\\.ya?ml$|\
          (^|.*/)(vars|tasks|handlers)/\
          "
        fail_fast: true
