default:
  image: ubuntu:latest

stages:
  - check

check-precommit:
  stage: check
  image: python:latest
  before_script:
    - echo -e "section_start:`date +%s`:install[collapsed=true]\r\e[0KInstall"
    - pip3 install pre-commit
    - echo -e "section_end:`date +%s`:install\r\e[0K"
  script:
    - git reset --soft HEAD~1
    - pre-commit run
  after_script:
    - git diff --color=always
    - |
      echo "If this pre-commit check failed, make sure that pre-commit is
      installed and enabled in your working repository:
      \$ pip3 install pre-commit
      \$ pre-commit install"
